### ISSUE TITLE
Roundup fails on Python packages whose dependencies include C extensions

### ISSUE THREAD

**Issue by nutjob4life** [NASA-PDS/roundup-action#3]
## 🐛 Describe the Bug

When the Roundup is used on a Python package that includes a dependency like `numpy`, i.e.,
```python
setup(…, install_requires=['numpy'], …)
```
and that dependency has C extensions, the assembly fails because the package setup needs `gcc` and other build tools at setup time.

## 📑 To Reproduce

Run the Roundup on [pds-doi-service](https://github.com/NASA-PDS/pds-doi-service).

Or more simply:

    docker container run --interactive --tty --rm --entrypoint /usr/local/bin/pip nasapds/pds-github-actions-base:latest install numpy

## 🔍 Expected Behavior

For the assembly to complete.

**Comment by nutjob4life** [comment]
Fixed in dde8c8223c3efa3682b40760d27a14a11e227c17

**Comment by tloubrieu-jpl** [comment]
Hi @nutjob4life , the action still fails on the pandas install for the pds-doi-service action:
ERROR: Failed building wheel for pandas\nERROR: Failed to build one or more wheels\nerror: Command '['/usr/local/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpzkqdb4t6', '--quiet', 'pandas>=1.0']' returned non-zero exit status 1.\n"»
Traceback (most recent call last):

See the full action log at https://github.com/NASA-PDS/pds-doi-service/actions/runs/338169191

Should I update something so that the new docker image is used ?

**Comment by nutjob4life** [comment]
@tloubrieu-jpl  I pushed another new base image to [Docker Hub](https://hub.docker.com/r/nasapds/pds-github-actions-base). Try it again!
